### ISSUE TITLE
send_request send_command

### ISSUE THREAD

**Issue by st0ll3n** [st0ll3n/icom7300_send_recieve#38]
I don't remember this todo:   is it still valid?

# todo: address converting the ser line below to an adjustable timeout. datatype error!

is the timeout adjustable?

**Comment by jafts** [comment]
radio.py still looks at radio_variables.xml for timeout value.   It can be adjusted by writing new value to radio_variables.xml<timeout>

**Comment by st0ll3n** [comment]
Thanks
